use crate::validation_rules::types::{
    common_rules, empty_coercions, ActionRule, EnumVals, FieldRule,
};

pub fn rule() -> ActionRule<'static> {
    ActionRule {
        model: "User",
        action: "update_user",
        version: "1",
        fields: vec![
            FieldRule {
                name: "name",
                r#type: "string",
                required: false,
                nullable: false,
                pii: true,
                min_len: Some(1),
                max_len: Some(120),
                pattern: None,
                r#enum: None,
                format: None,
                example: Some("Alex Doe"),
                ui: None,
            },
            FieldRule {
                name: "email",
                r#type: "string",
                required: false,
                nullable: false,
                pii: true,
                min_len: None,
                max_len: Some(254),
                pattern: None,
                r#enum: None,
                format: Some("email"),
                example: Some("alex@example.com"),
                ui: None,
            },
            FieldRule {
                name: "role",
                r#type: "string",
                required: false,
                nullable: false,
                pii: false,
                min_len: None,
                max_len: None,
                pattern: None,
                r#enum: Some(EnumVals {
                    values: &["admin", "user"],
                }),
                format: None,
                example: Some("user"),
                ui: None,
            },
            FieldRule {
                name: "company_ids",
                r#type: "array<string>",
                required: false,
                nullable: true,
                pii: false,
                min_len: None,
                max_len: None,
                pattern: None,
                r#enum: None,
                format: None,
                example: None,
                ui: None,
            },
            FieldRule {
                name: "active",
                r#type: "boolean",
                required: false,
                nullable: false,
                pii: false,
                min_len: None,
                max_len: None,
                pattern: None,
                r#enum: None,
                format: None,
                example: Some("true"),
                ui: None,
            },
            FieldRule {
                name: "preferences",
                r#type: "object",
                required: false,
                nullable: true,
                pii: false,
                min_len: None,
                max_len: None,
                pattern: None,
                r#enum: None,
                format: None,
                example: None,
                ui: None,
            },
            FieldRule {
                name: "last_active_company_id",
                r#type: "string",
                required: false,
                nullable: true,
                pii: false,
                min_len: None,
                max_len: Some(64),
                pattern: None,
                r#enum: None,
                format: None,
                example: Some("company_123"),
                ui: None,
            },
        ],
        coercions: empty_coercions(),
        rules: common_rules(),
    }
}
